// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8tMSuHiQyW_igpV_5UQRjhSAWcGKa_-M',
    appId: '1:554696038709:web:29698d138b31b316ced47c',
    messagingSenderId: '554696038709',
    projectId: 'isler-destek',
    authDomain: 'isler-destek.firebaseapp.com',
    databaseURL: 'https://isler-destek-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isler-destek.appspot.com',
    measurementId: 'G-6K1GPXSZ40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuMey9CCJBBh6ZWEvBHICeF52PAzP54CI',
    appId: '1:554696038709:android:37bcebf253e88dbaced47c',
    messagingSenderId: '554696038709',
    projectId: 'isler-destek',
    databaseURL: 'https://isler-destek-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isler-destek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvejc1gSagk5Lml0ltWlbB8hzL4lJqBu4',
    appId: '1:554696038709:ios:b8b8f5eeb6dabd6fced47c',
    messagingSenderId: '554696038709',
    projectId: 'isler-destek',
    databaseURL: 'https://isler-destek-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'isler-destek.appspot.com',
    androidClientId: '554696038709-4rtq1j6ob2lrso7kbrkdfmqaa02ea2b7.apps.googleusercontent.com',
    iosClientId: '554696038709-9g882km47mddnmlaa6aiuekffemf4mar.apps.googleusercontent.com',
    iosBundleId: 'com.vk.postbar',
  );
}
